%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\vi.vitale\PycharmProjects\pythonProject\UASOS\results\res_12062023_142117_ID100_t.csv
%
% Auto-generated by MATLAB on 12-Jun-2023 14:56:07

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 54);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TIME", "SWITCH", "TASK", "IMG_1", "IMG_2", "IMG_3", "IMG_4", "IMG_5", "IMG_6", "IMG_7", "IMG_8", "IMG_9", "FIL_1", "FIL_2", "FIL_3", "FIL_4", "FIL_5", "FIL_6", "FIL_7", "FIL_8", "FIL_9", "ROT_1", "ROT_2", "ROT_3", "ROT_4", "ROT_5", "ROT_6", "ROT_7", "ROT_8", "ROT_9", "COR_1", "COR_2", "COR_3", "COR_4", "COR_5", "COR_6", "COR_7", "COR_8", "COR_9", "USR_1", "USR_2", "USR_3", "USR_4", "USR_5", "USR_6", "USR_7", "USR_8", "USR_9", "LATENCY", "RT", "TTS", "Good_Ch", "Ov_Ch", "Ov_True"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
res = readtable("C:\Users\vi.vitale\PycharmProjects\pythonProject\UASOS\results\res_12062023_142117_ID100_t.csv", opts);


%% Clear temporary variables
clear opts

latency = res{:,49};
m = mean(latency);
dev_vec = (latency - m).^2;
x = [1:1:size(latency,1)];
var = sum(dev_vec)/size(dev_vec,1);
pop = sqrt(var);

f = gauss_distribution(latency, m, pop);

%% Fit: 'Latency Gaussian'.
[xData, yData] = prepareCurveData( latency, f );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.0836460515355377 25.3881798756775 1.68643362452584 0.0652192689487529 28.2951806862839 3.83495063259862];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Latency Gaussian' );
h = plot( fitresult, xData, yData );
legend( h, 'f vs. latency', 'Latency Gaussian', 'Location', 'NorthWest', 'Interpreter', 'none' );
% Label axes
xlabel( 'Latency [ms]', 'Interpreter', 'none' );
ylabel( 'Gauss Distribution', 'Interpreter', 'none' );
title('Latency distribution for SRCTask')
grid on

function f = gauss_distribution(x, mu, s)
p1 = -.5 * ((x - mu)/s).^2;
p2 = (s * sqrt(2*pi));
f = exp(p1) ./ p2;
end

