%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\vi.vitale\PycharmProjects\SurvTask\latency_test.txt
%
% Auto-generated by MATLAB on 01-Jun-2023 10:57:20

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "latency";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\vi.vitale\PycharmProjects\SurvTask\latency_test.txt", opts);

%% Convert to output type
latency = tbl.latency;

%% Clear temporary variables
clear opts tbl

x = [min(latency-10):0.1:max(latency+10)]';

[mu,s,muci,sci] = normfit(latency)
y = normpdf(x,mu,s);
plot(x,y,'b')
hold on
plot(latency, normpdf(latency,mu,s),'ro')

title('Latency distribution')
xlabel('Latency [msec]')
ylabel('Probability of occurrence [%]')